export enum FileMode {
  PROFILE_IMAGE = "0",
  PLAYBOOK_HEADER_IMAGE = "1",
  IMAGES_FOR_PLAYBOOK_PAGES = "2",
  PLAYBOOK_THUMBNAILS = "3",
  PLAYYBOOK_ICON = "4",
}

export enum MainTabs {
  All = 0,
  My = 1,
  Favorite = 2,
  Purchased = 3,
  Listings = 4,
}

export enum Modal {
  PLAYBOOK_DELETE = "PLAYBOOK_DELETE",
  PLAYBOOK_DETAILS = "PLAYBOOK_DETAILS",
  PLAYBOOK_SOCIAL = "PLAYBOOK_SOCIAL",
  PLAYBOOK_SHARE = "PLAYBOOK_SHARE",
  PAGE_DELETE = "PAGE_DELETE",
  ICONS = "ICONS",
  SIGN_UP = "SIGN_UP",
  PURCHASE = "PURCHASE",
}
